### ISSUE TITLE
Cannot compile typed context: The type X already contains a definition for 'Y'

### ISSUE THREAD

**Issue by jklosinski** [kenakamu/CRMLinqPadDriverWebAPI#1]
I finally managed to connected to my org using the consent path (the thing that tripped me up was that after specifying the permissions for the application I didn't realize I had to hit save).

LINQPad downloaded metadata and then I got this error:

![image](https://cloud.githubusercontent.com/assets/1887185/14619729/7f2ed5c0-057e-11e6-8d24-6cc41bc58646.png)

System.Exception

Cannot compile typed context: The type 'Microsoft.Dynamics.CRM.msdyn_surveyinviteSingle' already contains a definition for 'regardingobjectid_msdyn_surveyresponse' (line 308456)

Is there anything I can do?

**Comment by kenakamu** [comment]
Thanks for the issue. This is known issue that you have duplicate schema name between field and relationship. As C# class cannot have same name property, there is nothing we can do at the moment. 

I am planning to implement selector (Entity and relationship) so that you can only include minimum amount of Entities later.

**Comment by kenakamu** [comment]
Can you try latest version?
